name: flutter_tetris
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.1.1
  intl: ^0.18.1
  path: ^1.8.3
  responsive_sizer: ^3.1.1
  sqflite: ^2.2.8+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
  
  fonts:
    - family: VT323
      fonts:
        - asset: assets/fonts/VT323.ttf
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P.ttf
